USE codeup_test_db;
CREATE TABLE albums(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR (50) NOT NULL,
name VARCHAR (100) NOT NULL,
release_date YEAR(4),
sales DECIMAL(8,2) NOT NULL,
genre VARCHAR (50),
PRIMARY KEY (id)
);